version: '3.8'

services:
  # Serwer aplikacji PHP + Apache
  web:
    image: php:8.2-apache
    container_name: todolist-web
    ports:
      - "{WEB_PORT}:80"  # Strona dostępna pod http://localhost:8000
    volumes:
      - ./public:/var/www/html           # Publiczny katalog www
      - ./app:/var/www/app               # Katalog z logiką aplikacji (niewidoczny z zewnątrz)
      - ./config:/var/www/config               # Klasy, modele itp.
      - ./vendor:/var/www/vendor         # Zależności Composera
      - ./storage:/var/www/storage
      - ./.env:/var/www/.env 
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini  # Konfiguracja PHP (opcjonalna)
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

  # Serwer MySQL
  db:
    image: mysql:8.0
    container_name: todolist-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      MYSQL_DATABASE=${DB_NAME}
      MYSQL_USER=${DB_USER}
      MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql

    ports:
      - "3306:3306"  # Dostęp do bazy np. z DataGrip lub DBeaver

  # phpMyAdmin – GUI do zarządzania MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: settlerswars-pma
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"  # phpMyAdmin dostępny pod http://localhost:8080
    environment:
      - PMA_HOST=db               # Nazwa usługi MySQL z docker-compose
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
