CREATE DATABASE IF NOT EXISTS todolist_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE todolist_db;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (email, password) VALUES
('john@todo.com', '$2y$10$3E5zocfsqqFHPUNfsEDeXuTC3mFrJkTrSRNVkfS1uuK0trrL1Xrr2'),
('lisa@todo.com', '$2y$10$SRULDFTaye5J1Irp0sBZO.S/7Btj2BAffKltPqfiBSO0m3mlFNvCi');




